### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by jjeff** [ipinfo/node-express#9]
I'd love to use this library in my Typescript-based project. But the project has no type definition files and there don't seem to be any in the Definitely Typed repository either.

It looks like https://github.com/ipinfo/node has type definitions. How about adding them here too?

**Comment by UmanShahzad** [comment]
Yeah the Nodejs SDK has it because it's in Typescript already, but this one is in plain JS. We'll add something, though it'll take some time, or if you can contribute we'll accept a PR.

**Comment by UmanShahzad** [comment]
Latest version has TS support.
